package jzy.taining.plugins.jspark.features.templates.templates

import jzy.taining.plugins.jspark.features.templates.data.TemplateValues

fun jsparkJViewBean(templateValues: TemplateValues) =
    """
package ${templateValues.packageName}

import first.lunar.yun.adapter.face.OnViewClickListener
import first.lunar.yun.adapter.holder.JViewHolder
import first.lunar.yun.adapter.vb.JViewBean
import ${templateValues.applicationId}.R

/**
 *  generated by jspark
 */
class ${templateValues.viewBeanName}: JViewBean() {

     override fun bindLayout() = R.layout.${templateValues.viewBeanLayoutName}
     
     override fun onBindViewHolder(holder: JViewHolder?, position: Int, payloads: MutableList<Any>?, clickListener: OnViewClickListener<*>?) {
        TODO("更新 UI")
    }
    
}
    """