package jzy.taining.plugins.jspark.features.templates.templates

import jzy.taining.plugins.jspark.features.templates.data.TemplateValues

fun jsparkViewmodel(templateValues: TemplateValues) =
    """
package ${templateValues.packageName}

import android.app.Application
import io.reactivex.disposables.Disposable
import com.gene.demo.basic.BasicViewModel
import com.gene.demo.data.NetResult
import ${templateValues.fullViewBeanName}

/**
 *  generated by jspark
 */
class ${templateValues.viewModelName}(application: Application?, param: Any?): BasicViewModel<${templateValues.viewBeanName}>(application, param) {

    override fun onPullData(param: Any?): Disposable {
        TODO("业务逻辑请求数据")
        return Observable.just(NetResult.newNetResultSuccess(BusiViewBean())).subscribe(this::onNetSucceed,this::onNetError)
    }
    
}
    """