package jzy.taining.plugins.jspark.features.templates.templates

import jzy.taining.plugins.jspark.features.templates.data.TemplateValues

fun jsparkLayout(templateValues: TemplateValues)=
"""<?xml version="1.0" encoding="utf-8"?>
<!--generated by jspark -->
<androidx.constraintlayout.widget.ConstraintLayout
        xmlns:android="http://schemas.android.com/apk/res/android"
        xmlns:tools="http://schemas.android.com/tools"
        xmlns:app="http://schemas.android.com/apk/res-auto"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        tools:context="${templateValues.fullActivityName}">


</androidx.constraintlayout.widget.ConstraintLayout>"""